language: java

jdk:
  - openjdk13

sudo: false

env:
  global:
    - CODECOV_TOKEN="ef9084ab-61dd-4b3d-848d-194e96837fc6"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - sash-2007@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always